(load "0-dominio.clp")
(load "1-main.clp")
(load "2-domande.clp")
(load "3-regole.clp")
(load "4-punteggio.clp")
(load "5-creazioneTour.clp")
(load "6-stampa.clp")
(load "7-domandeSecondarie.clp")
(reset)
(run)
